spring:
  application:
    name: track-service

  data-source:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  liquibase:
    parameters:
      textColumnType: TEXT
    changeLog: "classpath:db/changelog/changelog-main.xml"