spring:
  application:
    name: rating-service
  data-source:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  liquibase:
    parameters:
      textColumnType: TEXT
    changeLog: "classpath:db/changelog/changelog-main.xml"